# Generated by Django 2.2.16 on 2022-06-22 21:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('a08569c8-c431-4bea-88a4-f0610cefdfca'), verbose_name='UUID'),
        ),
    ]
